// ============================================================================
// AutoDiscovery — DiscoveryStep Entity
// An individual discovery obligation within a case.
// Each step maps to a specific rule (e.g., IRCP Rule 33 interrogatories)
// and has its own deadline, status, and compliance tracking.
// ============================================================================

import { StepStatus, StepCategory, RuleType, JurisdictionLevel } from "./enums";
import { DeadlineSpec, ComputedDeadline } from "./deadline";

/**
 * A single discovery step/obligation within a case.
 *
 * Generated automatically when a case is created — the rule loader
 * reads the jurisdiction rule pack and creates one DiscoveryStep
 * per applicable rule.
 *
 * On-chain representation:
 *   - stepHash: Field (hash of caseId + ruleRef)
 *   - completed: Boolean (in stepCompletionFlags ledger)
 *   - status: Uint<8> (in stepStatuses ledger)
 *   - deadline: Field (timestamp in stepDeadlines ledger)
 */
export interface DiscoveryStep {
  /**
   * Unique identifier — deterministic hash of caseId + ruleRef.
   * Matches the on-chain Field value computed by computeStepHash witness.
   */
  readonly stepId: string;

  /** The case this step belongs to */
  readonly caseId: string;

  /**
   * Reference to the rule that generated this step.
   * Format: "IRCP-26a", "FRCP-33", etc.
   * Used as input to computeStepHash.
   */
  readonly ruleId: string;

  /**
   * Human-readable rule reference (e.g., "IRCP Rule 26(a)").
   * Displayed in the UI for attorney reference.
   */
  readonly ruleRef: string;

  /** Category of this step — groups steps in the UI checklist */
  readonly category: StepCategory;

  /** Short description of the obligation (from rule pack) */
  readonly description: string;

  /** Whether this step is mandatory, optional, or conditional */
  readonly ruleType: RuleType;

  /** Current status of this step */
  status: StepStatus;

  /**
   * The deadline specification from the rule pack (relative).
   * Example: { offset: 30, unit: "calendarDays", fromEvent: "joinder-deadline" }
   */
  readonly deadlineSpec: DeadlineSpec;

  /**
   * The computed absolute deadline (output of deadline engine).
   * Null if the trigger event hasn't occurred yet
   * (e.g., deposition deadline can't be computed until scheduling order is entered).
   */
  computedDeadline: ComputedDeadline | null;

  /**
   * Which jurisdiction level this step originates from.
   * Used for override chain: federal → state → county → judge.
   */
  readonly source: JurisdictionLevel;

  /**
   * IDs of steps this step depends on.
   * Step can't start until dependencies are completed.
   * Example: expert disclosure depends on initial disclosures.
   */
  readonly dependsOn: string[];

  /**
   * Whether this step has been objected to by opposing counsel.
   * If true, status should be "objected" and objectionDetails populated.
   */
  isObjected: boolean;

  /** Details of any objection filed against this step */
  objectionDetails: string | null;

  /**
   * Whether this step is protected by privilege.
   * If true, must appear on the privilege log.
   */
  isPrivileged: boolean;

  /** Privilege log entry reference, if applicable */
  privilegeLogReference: string | null;

  /**
   * Whether this step has been waived (by agreement or court order).
   */
  isWaived: boolean;

  /** Reason for waiver, if applicable */
  waiverReason: string | null;

  /**
   * Set number for tracking supplementation.
   * Per Spy: attorneys sometimes use incorrect set numbers when collecting
   * supplementation to records. This tracks which "set" this request belongs to
   * (e.g., "First Set", "Second Set" for interrogatories).
   */
  setNumber: number | null;

  /**
   * Whether this step is a supplementation of a prior response.
   * Per IRCP Rule 26(e), parties must supplement prior disclosures.
   */
  readonly isSupplementation: boolean;

  /** If this is a supplementation, the original step it supplements */
  readonly supplementsStepId: string | null;

  /** Date this step was completed (null if not yet completed) */
  completedAt: Date | null;

  /** Who marked this step complete (attorney name or user ID) */
  completedBy: string | null;

  /**
   * On-chain attestation hash for this step's compliance proof.
   * Generated by the compliance-proof contract when step is attested.
   * Null until attestation is created.
   */
  attestationHash: string | null;

  /** Sanctions reference if this step triggered sanctions (IRCP Rule 37) */
  sanctionsReference: string | null;

  /** Notes — free-form field for attorney annotations */
  notes: string | null;

  /** When this step record was created */
  readonly createdAt: Date;

  /** Last update timestamp */
  updatedAt: Date;
}
